#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jsr311-api
Version  : 1.1.1
Release  : 1
URL      : https://repo1.maven.org/maven2/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
Source0  : https://repo1.maven.org/maven2/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
Source1  : https://repo1.maven.org/maven2/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0
Requires: mvn-jsr311-api-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jsr311-api package.
Group: Data

%description data
data components for the mvn-jsr311-api package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.pom
